version: "3.8"

networks:
  nginx_net:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_database:
    file: ./secrets/mysql_database.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

services:
  nginx:
    image: nginx:1.25.3-alpine3.18
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./xprob:/var/www/xprob
      - ./codigo-cassinov3/codigofonte:/var/www/cassinov3
    networks:
      - nginx_net

  xprob-app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/xprob
    volumes:
      - ./xprob:/var/www/xprob
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nginx_net
    depends_on:
      - mysql
      - redis

  cassino-local-v3:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./codigo-cassinov3/codigofonte:/var/www/cassinov3
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nginx_net
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - nginx_net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_database
      - mysql_root_password
      - mysql_user
      - mysql_password

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8888:80
    networks:
      - nginx_net
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  redis:
    image: redis:7.0
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >password ~* allcommands --user default off nopass nocommands",
      ]
    networks:
      - nginx_net
    ports:
      - 6379:6379
